/* Generated By:JavaCC: Do not edit this line. ESQueryTransformerConstants.java */
package com.qzy.javacc.es;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ESQueryTransformerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BETWEEN = 6;
  /** RegularExpression Id. */
  int IS = 7;
  /** RegularExpression Id. */
  int NULL = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int IN = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int LPAREN = 12;
  /** RegularExpression Id. */
  int RPAREN = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int IDENTIFIER = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int OPERATOR = 19;
  /** RegularExpression Id. */
  int OPERAND = 20;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 21;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<BETWEEN>",
    "<IS>",
    "<NULL>",
    "<NOT>",
    "<IN>",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<AND>",
    "<OR>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<OPERATOR>",
    "<OPERAND>",
    "\"\\\'\"",
    "\"\\\"\"",
  };

}
